//! Coverage-guided stateful fuzzing of the AMM liquidity pool.
//!
//! Interprets fuzzer-generated bytes as a sequence of pool operations and runs
//! them through the shared harness (`amm::fuzz_harness`), which asserts the
//! state invariants (reserves == balances, token conservation, implied rate
//! sanity) after every step. Run under WSL/Linux:
//!
//!     cargo +nightly fuzz run amm_stateful
//!
//! See fuzz/README.md for details.

#![no_main]

use arbitrary::Arbitrary;
use libfuzzer_sys::fuzz_target;

use amm::fuzz_harness::{run_steps, Step};

/// Raw fuzzer-facing step. Amounts are i64 (±9.2e18 spans everything from dust
/// to far beyond the pool's holdings) mapped into the harness's i128 steps.
#[derive(Arbitrary, Debug)]
enum RawStep {
    Deposit { actor: u8, pt: i64, v: i64 },
    Withdraw { actor: u8, shares: i64 },
    SwapVForPt { actor: u8, pt_out: i64, v_in_max: i64 },
    SwapPtForV { actor: u8, pt_in: i64, min_v_out: i64 },
    AdvanceTime { secs: u32 },
    SetVaultRate { rate: i64 },
}

impl From<&RawStep> for Step {
    fn from(raw: &RawStep) -> Self {
        match *raw {
            RawStep::Deposit { actor, pt, v } => Step::Deposit {
                actor,
                pt: pt.into(),
                v: v.into(),
            },
            RawStep::Withdraw { actor, shares } => Step::Withdraw {
                actor,
                shares: shares.into(),
            },
            RawStep::SwapVForPt { actor, pt_out, v_in_max } => Step::SwapVForPt {
                actor,
                pt_out: pt_out.into(),
                v_in_max: v_in_max.into(),
            },
            RawStep::SwapPtForV { actor, pt_in, min_v_out } => Step::SwapPtForV {
                actor,
                pt_in: pt_in.into(),
                min_v_out: min_v_out.into(),
            },
            RawStep::AdvanceTime { secs } => Step::AdvanceTime { secs: secs.into() },
            RawStep::SetVaultRate { rate } => Step::SetVaultRate { rate: rate.into() },
        }
    }
}

#[derive(Arbitrary, Debug)]
struct Input {
    steps: Vec<RawStep>,
}

fuzz_target!(|input: Input| {
    // Bound sequence length so the fuzzer explores many scenarios rather than
    // spending its budget on one enormous one.
    let steps: Vec<Step> = input.steps.iter().take(64).map(Step::from).collect();
    run_steps(&steps);
});