[workspace]
resolver = "2"
members = [
  "contracts/factory",
  "contracts/tokens/principal_token",
  "contracts/tokens/principal_token_interface",
  "contracts/tokens/yield_token",
  "contracts/tokens/yield_token_interface",
  "contracts/yield/yield_manager",
  "contracts/yield/yield_manager_interface",
  "contracts/mocks/mock_vault",
  "vault/vault_interface",
  "vault/defindex_interface",
]

[workspace.dependencies]
soroban-sdk = "25.3.1"
soroban-token-sdk = "25.3.1"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

# For more information about this profile see https://soroban.stellar.org/docs/basic-tutorials/logging#cargotoml-profile
[profile.release-with-logs]
inherits = "release"
debug-assertions = true
