// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
    datasource: {
        url: "postgresql://ybc:wAHElT4RS0QU@localhost:5432/ybc_indexer",
    },
});
