// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import { PrismaPg } from "@prisma/adapter-pg";

export default defineConfig({
    earlyAccess: true,
    datasource: {
        adapter: () =>
            new PrismaPg({
                connectionString:
                    "postgresql://ybc:wAHElT4RS0QU@localhost:5432/ybc_indexer",
            }),
    },
});
