[package]
name = "factory"
version = "0.1.3"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
soroban-sdk = { workspace = true }
stellar-access = { workspace = true }
stellar-macros = { workspace = true }
yield_manager_interface = { path = "../yield/yield_manager_interface" }
factory_interface = { workspace = true }
ybc_common = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
mock_vault = { path = "../mocks/mock_vault" }
