[package]
name = "factory"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
soroban-sdk = { workspace = true }
yield_manager_interface = { path = "../yield/yield_manager_interface" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
mock_vault = { path = "../mocks/mock_vault" }
