[package]
name = "router"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { workspace = true }
amm-interface = { path = "../amm/amm-interface" }
yield_manager_interface = { path = "../yield/yield_manager_interface" }
yield_token_interface = { path = "../tokens/yield_token_interface" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }